### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by olexandr-konovalov** [dolphin-acoustics-vip/artwarp#7]
@vmjanik @vdeecke I recommend to choose a license - please see e.g. https://choosealicense.com/

**Comment by alex-konovalov** [comment]
P.S. More licenses are available on the choosealicense website, but they are not well signposted from the main page - see https://choosealicense.com/appendix/.

**Comment by alex-konovalov** [comment]
Copying here what I wrote earlier, to keep it closer to the code, and have a documented decision making trail.

I am not a lawyer, but I think there may be a problem with GPL for ARTWarp since the code has to be used under MATLAB,which is nonfree.

These two answers:
- https://stackoverflow.com/questions/3735389/can-i-license-my-matlab-code-using-the-gpl 
- https://opensource.stackexchange.com/questions/4887/is-it-appropriate-to-use-open-source-license-with-matlab-code

recommend to use BSD license. The BSD license is even used by MathWorks File Exchange:
- https://uk.mathworks.com/matlabcentral/content/fx/fx-transition-faq.html
- https://uk.mathworks.com/matlabcentral/content/terms-of-use.html#filex

so it seems to me like a suitable choice (more on BSD license at https://opensource.org/licenses/bsd-license.php). Other appropriate choices could be LGPL (GNU Lesser General Public License) or Apache 2.0 - see https://choosealicense.com/appendix/ for their comparison. The final decision of course is with the ARTWarp authors.

When decided, one should find a text file with the text of the license and add it to the repository - also a good exercise to practice commits and pull requests.

**Comment by alex-konovalov** [comment]
@vmjanik @vdeecke do you agree on BSD license then, or would like more time and information to make a decision?

**Comment by alex-konovalov** [comment]
@vmjanik @vdeecke We need to come to a conclusion here - it wouldn't be a good practice to publish an official release which does not have a license.

**Comment by olexandr-konovalov** [comment]
@vmjanik @vdeecke ping?

**Comment by vmjanik** [comment]
Hi Olexandr,
I think we will go for the LGPL license which is for libraries that run within other software. 
Thank you.
